import Head from "next/head";
import Image from "next/image";
import Collumns from "../components/Collumns";
import styles from "../styles/Home.module.css";
import Cards from "../components/Cards";
import Footer from "../components/Footer";
import { useState, useEffect } from "react";
import AOS from "aos";
export default function Home() {
  const [stop, setstop] = useState(false);
  const [text, setText] = useState("");
  const [fullText, setFullText] = useState(
    "I design and code beautifully simple things, and I hate what I do."
  );
  const [index, setIndex] = useState(0);
  useEffect(() => {
    if (text !== fullText && stop === false) {
      setTimeout(() => {
        setText(text + fullText[index]);
        setIndex(index + 1);
      }, 50);
    } else {
      setFullText(
        "I design and code beautifully simple things, and I love what I do."
      );
      setText("I design and code beautifully simple things,");
      setIndex(44);
      if (text !== fullText && stop === false) {
        setTimeout(() => {
          setText(text + fullText[index]);
          setIndex(index + 1);
        }, 75);
      }
      if (
        text ===
        "I design and code beautifully simple things, and I love what I do."
      ) {
        setstop(true);
        setText(fullText);
      }
    }
  }, [index]);
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <div>
      <Head>
        <title>Gouder Haithem | Home Page </title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="google-site-verification"
          content="272DPjWmzvUkeaJA3_wLp819E5yNTT8AhlMGIZqLaZM"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Gouder Haithem's portofolio created by gouder Haithem"
        ></meta>
      </Head>
      <main className={`${styles.main}`}>
        <header data-aos="fade-up" className={styles.header}>
          <h1 data-aos="fade-up">Software Engineer</h1>
          <p data-aos="fade-up">{text}</p>
          <Image
            data-aos="fade-up"
            width={330}
            height={300}
            className={styles.avatar}
            src={"/my-avatar.svg"}
            layout="fill"
            alt="avatart"
            loading="eager"
          />
          <Image
            width={630}
            loading="eager"
            height={400}
            className={styles.home_bg}
            src={"/home-bg.svg"}
            alt="hero-image-logo"
            layout="fill"
          />
        </header>
        <section className={styles.main_section}>
          <h1 data-aos="fade-up">Hi, I'm Gouder. Nice to meet you.</h1>
          <p data-aos="fade-up">
            Hello! I am Gouder Haithem, a recent graduate with a Master's degree
            in Computer Science, specializing in New Technology of Information
            and Communication. I have a strong passion for technology and have
            developed expertise in Web and Mobile development, IoT and AI. My
            goal is to contribute to technological advancements by leveraging my
            skills and knowledge to create innovative solutions in the
            Information and Communication Technology sector. I am dedicated,
            eager to learn, and ready to make a significant impact in this
            ever-evolving field.
          </p>
        </section>
        <Collumns />
        <div className={styles.projects_text}>
          <h1>My Recent work </h1>
          <p>
            Here are a few past projects I've worked on. Want to see more?
            <a
              style={{ color: "#0068d1", fontWeight: "bold" }}
              href="https://github.com/haithemgouder"
              target={"_blank"}
              rel="noreferrer"
            >
              {" "}
              View more projects.
            </a>
          </p>
        </div>
        <Cards />
        <Footer />
      </main>
    </div>
  );
}
