import Head from "next/head";
import Image from "next/image";
import Collumns from "../components/Collumns";
import styles from "../styles/Home.module.css";
import Cards from "../components/Cards";
import Footer from "../components/Footer";
import { useState, useEffect } from "react";
import AOS from "aos";
export default function Home() {
  const [stop, setstop] = useState(false);
  const [text, setText] = useState("");
  const [fullText, setFullText] = useState(
    "I design and code beautifully simple things, and I hate what I do."
  );
  const [index, setIndex] = useState(0);
  useEffect(() => {
    if (text !== fullText && stop === false) {
      setTimeout(() => {
        setText(text + fullText[index]);
        setIndex(index + 1);
      }, 50);
    } else {
      setFullText(
        "I design and code beautifully simple things, and I love what I do."
      );
      setText("I design and code beautifully simple things,");
      setIndex(44);
      if (text !== fullText && stop === false) {
        setTimeout(() => {
          setText(text + fullText[index]);
          setIndex(index + 1);
        }, 75);
      }
      if (
        text ===
        "I design and code beautifully simple things, and I love what I do."
      ) {
        setstop(true);
        setText(fullText);
      }
    }
  }, [index]);
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <div>
      <Head>
        <title>Gouder Haithem | Home Page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Gouder Haithem's portofolio created by gouder Haithem"
        ></meta>
      </Head>
      <main className={`${styles.main}`}>
        <header data-aos="fade-up" className={styles.header}>
          <h1 data-aos="fade-up">Cs Student & Future Programmer</h1>
          <p data-aos="fade-up">{text}</p>
          <Image
            data-aos="fade-up"
            width={330}
            height={300}
            className={styles.avatar}
            src={"/my-avatar.svg"}
            layout="fill"
            alt="avatart"
            loading="eager"
          />
          <Image
            width={630}
            loading="eager"
            height={400}
            className={styles.home_bg}
            src={"/home-bg.svg"}
            alt="hero-image-logo"
            layout="fill"
          />
        </header>
        <section className={styles.main_section}>
          <h1 data-aos="fade-up">Hi, I'm Gouder. Nice to meet you.</h1>
          <p data-aos="fade-up">
            Hello there! I'm Gouder Haithem, currently immersed in the pursuit
            of a Master's degree in Computer Science, specializing in the
            innovative realm of New Technology of Information and Communication.
            Passionate about exploring cutting-edge advancements, I am actively
            engaged in honing my skills in areas such as Web and Mobile
            development, IoT, Ai cloud computing .within this dynamic field.
            Eager to contribute to the ever-evolving landscape of technology,
            I'm poised to leverage my expertise and learning to drive meaningful
            advancements in Information and Communication technologies upon
            completion of my degree.
          </p>
        </section>
        <Collumns />
        <div className={styles.projects_text}>
          <h1>My Recent work </h1>
          <p>
            Here are a few past projects I've worked on. Want to see more?
            <a
              style={{ color: "#0068d1", fontWeight: "bold" }}
              href="https://github.com/haithemgouder"
              target={"_blank"}
              rel="noreferrer"
            >
              {" "}
              View more projects.
            </a>
          </p>
        </div>
        <Cards />
        <Footer />
      </main>
    </div>
  );
}
